version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
      platform: "linux/amd64"
      build:
        context: .
        dockerfile: Dockerfile
        args:
          NEXT_PUBLIC_CLIENTVAR: "clientvar"
      working_dir: /app
      ports:
        - "5628:3000"
      image: kareigu/shared-list:latest
      environment:
        - DATABASE_URL=postgresql://postgres:example@db:5432
        - VERCEL_URL=list.karei.dev
        - VERCEL=TRUE
      volumes:
        - .env:/app/.env
